<#
.SYNOPSIS
    Configures IIS Web Site Bindings and Windows Firewall for iDash listening port and protocol.
.DESCRIPTION
    Generated by iDash Site Configuration (va_site_config.aspx).
    Configures IIS web bindings for port 8181 (http),
    adds Windows Firewall rule, and restarts the IIS web site.
    Must be executed with elevated Administrator privileges.
#>
[CmdletBinding()]
param(
    [int]$Port = 8181,
    [ValidateSet("http", "https")]
    [string]$Protocol = "http",
    [string]$SiteName = "",
    [string]$CertThumbprint = ""
)

# 1. Ensure Administrator Elevation
$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Warning "Administrator elevation required. Relaunching in elevated window..."
    Start-Process powershell.exe -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`"" -Verb RunAs
    exit
}

Write-Host "=================================================================" -ForegroundColor Cyan
Write-Host " iDash Server Port & IIS Binding Rollout Script" -ForegroundColor White
Write-Host " Protocol: $Protocol | Port: $Port" -ForegroundColor Yellow
Write-Host " Target Base URL: http://localhost:8181" -ForegroundColor Cyan
Write-Host "=================================================================" -ForegroundColor Cyan

# 2. Import IIS Administration Module
try {
    Import-Module WebAdministration -ErrorAction Stop
} catch {
    Write-Error "Failed to import WebAdministration module. Please ensure IIS Management Scripts and Tools are installed."
    Read-Host "Press Enter to exit"
    exit 1
}

# 3. Detect IIS Site
if ([string]::IsNullOrWhiteSpace($SiteName)) {
    if (Get-Website | Where-Object { $_.Name -eq "iDash" }) {
        $SiteName = "iDash"
    } elseif (Get-Website | Where-Object { $_.Name -eq "Default Web Site" }) {
        $SiteName = "Default Web Site"
    } else {
        $firstSite = (Get-Website | Select-Object -First 1)
        if ($firstSite) {
            $SiteName = $firstSite.Name
        } else {
            Write-Error "No IIS websites found on this server."
            Read-Host "Press Enter to exit"
            exit 1
        }
    }
}

Write-Host "Target IIS Site: '$SiteName'" -ForegroundColor Green

# 4. Check existing bindings
$existingBindings = Get-WebBinding -Name $SiteName
Write-Host "`nCurrent Bindings for '$SiteName':" -ForegroundColor Gray
$existingBindings | ForEach-Object {
    Write-Host "  - $($_.protocol)://$($_.bindingInformation)" -ForegroundColor DarkGray
}

$bindingMatch = $existingBindings | Where-Object {
    $_.protocol -eq $Protocol -and ($_.bindingInformation -like "*:$Port:*" -or $_.bindingInformation -like "*:$Port")
}

if ($bindingMatch) {
    Write-Host "`n[OK] Binding already exists for $Protocol on port $Port." -ForegroundColor Green
} else {
    Write-Host "`n[ACTION] Adding new WebBinding: $Protocol on port $Port..." -ForegroundColor Yellow
    New-WebBinding -Name $SiteName -IPAddress "*" -Port $Port -Protocol $Protocol -ErrorAction Stop
    Write-Host "[OK] Binding added successfully." -ForegroundColor Green
}

# 5. Handle SSL / HTTPS Certificate Binding if port 443 / https
if ($Protocol -eq "https") {
    Write-Host "`n--- Configuring SSL / TLS Certificate for Port $Port ---" -ForegroundColor Cyan
    $cert = $null
    if (-not [string]::IsNullOrWhiteSpace($CertThumbprint)) {
        $cert = Get-Item "Cert:\LocalMachine\My\$CertThumbprint" -ErrorAction SilentlyContinue
    }
    if (-not $cert) {
        $cert = Get-ChildItem "Cert:\LocalMachine\My" | Where-Object { $_.Subject -like "*$env:COMPUTERNAME*" -or $_.Subject -like "*localhost*" -or $_.Subject -like "*iDash*" } | Select-Object -First 1
    }

    if ($cert) {
        Write-Host "Using SSL Certificate: $($cert.Subject) [Thumbprint: $($cert.Thumbprint)]" -ForegroundColor Green
        try {
            $existingSsl = Get-ChildItem "IIS:\SslBindings" | Where-Object { $_.Port -eq $Port }
            if ($existingSsl) {
                Write-Host "Replacing existing SSL binding on port $Port..." -ForegroundColor Yellow
                $existingSsl | Remove-Item
            }
            Get-Item "Cert:\LocalMachine\My\$($cert.Thumbprint)" | New-Item "IIS:\SslBindings\0.0.0.0!$Port" -Force | Out-Null
            Write-Host "[OK] SSL Certificate bound to 0.0.0.0:$Port." -ForegroundColor Green
        } catch {
            Write-Warning "Could not automatically bind SSL certificate via IIS:\SslBindings: $_"
            Write-Host "You can assign the certificate manually in IIS Manager -> Bindings -> Edit port 443." -ForegroundColor Yellow
        }
    } else {
        Write-Warning "No SSL certificate found in Cert:\LocalMachine\My. Please assign your SSL certificate in IIS Manager -> Bindings -> Edit port $Port."
    }
}

# 6. Windows Firewall Rule
Write-Host "`n--- Configuring Windows Firewall ---" -ForegroundColor Cyan
$ruleName = "iDash Web Server ($Protocol Port $Port)"
$existingRule = Get-NetFirewallRule -DisplayName $ruleName -ErrorAction SilentlyContinue
if (-not $existingRule) {
    try {
        New-NetFirewallRule -DisplayName $ruleName -Name "iDash_Port_$Port" -Direction Inbound -LocalPort $Port -Protocol TCP -Action Allow -Profile Any -ErrorAction Stop | Out-Null
        Write-Host "[OK] Windows Firewall inbound rule created for TCP port $Port." -ForegroundColor Green
    } catch {
        Write-Warning "Could not add firewall rule automatically: $_"
    }
} else {
    Write-Host "[OK] Windows Firewall inbound rule already active for Port $Port." -ForegroundColor Green
}

# 7. Restart IIS Site
Write-Host "`n--- Restarting IIS Site ---" -ForegroundColor Cyan
try {
    Restart-WebItem "IIS:\Sites\$SiteName" -ErrorAction SilentlyContinue
    Write-Host "[OK] IIS Site '$SiteName' restarted." -ForegroundColor Green
} catch {
    Write-Warning "Could not restart IIS site automatically: $_"
}

Write-Host "`n=================================================================" -ForegroundColor Green
Write-Host " Rollout Completed!" -ForegroundColor White
Write-Host " iDash is now listening on $Protocol://*:$Port/" -ForegroundColor Yellow
Write-Host " Test URL: $Protocol://localhost:$Port/" -ForegroundColor White
Write-Host "=================================================================" -ForegroundColor Green
