using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Mail;
using System.Text;
using System.Web;

public partial class va_universal_ennx : System.Web.UI.Page
{
    private const string FILE_PREFIX = "ennx_universal_";

    protected void Page_Load(object sender, EventArgs e)
    {
        // Auth check
        bool isLoggedIn = Session["IsAdminAuthenticated"] != null && (bool)Session["IsAdminAuthenticated"];
        if (!isLoggedIn)
        {
            Response.Redirect("index.aspx?returnUrl=" + Server.UrlEncode(Request.RawUrl));
            return;
        }

        // Tile check
        var tiles = Session["IdashTileAccess"] as List<string>;
        string role = Convert.ToString(Session["IdashUserRole"]);
        if (!UserManager.CanAccessTile(role, tiles, "scan_universal_ennx"))
        {
            Response.Redirect("index.aspx?err=access");
            return;
        }

        if (!IsPostBack)
        {
            // Store the iDash username for email subject attribution
            HidUser.Value = Convert.ToString(Session["IdashUsername"] ?? "");
        }
    }

    // -------------------------------------------------------
    // Download: stream ENNX file directly to browser
    // -------------------------------------------------------
    protected void BtnDownload_Click(object sender, EventArgs e)
    {
        string ennx = (HidEnnx.Value ?? "").Trim();
        if (string.IsNullOrWhiteSpace(ennx))
        {
            ShowMsg("No ENNX data yet. Scan at least one location and asset first.", true);
            return;
        }

        string stamp = DateTime.Now.ToString("yyyyMMdd_HHmmss");
        string fname = FILE_PREFIX + stamp + ".txt";

        Response.Clear();
        Response.ContentType = "text/plain";
        Response.AddHeader("Content-Disposition", "attachment; filename=" + fname);
        Response.ContentEncoding = Encoding.UTF8;
        Response.Write(ennx);
        Response.End();
    }

    // -------------------------------------------------------
    // Email: send ENNX as attachment to configured recipients
    // -------------------------------------------------------
    protected void BtnEmail_Click(object sender, EventArgs e)
    {
        string ennx    = (HidEnnx.Value    ?? "").Trim();
        string summary = (HidSummary.Value ?? "").Trim();
        string user    = (HidUser.Value    ?? "").Trim();

        if (string.IsNullOrWhiteSpace(ennx))
        {
            ShowMsg("No ENNX data to email yet.", true);
            return;
        }

        try
        {
            string stamp = DateTime.Now.ToString("yyyyMMdd_HHmmss");
            string fname = FILE_PREFIX + stamp + ".txt";

            byte[] bytes = Encoding.UTF8.GetBytes(ennx);
            using (var stream = new MemoryStream(bytes))
            {
                var attachment  = new Attachment(stream, fname, "text/plain");
                var attachments = new List<Attachment> { attachment };

                string who     = string.IsNullOrWhiteSpace(user) ? "iDash Portal" : user;
                string subject = string.Format("Universal ENNX Export — {0} — {1}",
                                               who, DateTime.Now.ToString("yyyy-MM-dd"));
                string body = string.Format(@"
                    <h3>Universal ENNX Creator Export</h3>
                    <p><b>Generated by:</b> {0}</p>
                    <p><b>Date:</b> {1}</p>
                    <p><b>Summary:</b> {2}</p>
                    <p>See attached <code>.txt</code> file for the complete ENNX output.</p>
                    <hr/>
                    <p><small>Sent from iDash Universal ENNX Creator.</small></p>",
                    HttpUtility.HtmlEncode(who),
                    DateTime.Now.ToLongDateString(),
                    HttpUtility.HtmlEncode(summary));

                EmailHelper.SendEmail(subject, body, attachments);
                ShowMsg("Email sent successfully with attachment <strong>" +
                        HttpUtility.HtmlEncode(fname) + "</strong>.", false);
            }
        }
        catch (Exception ex)
        {
            ShowMsg("Email failed: " + HttpUtility.HtmlEncode(ex.Message), true);
        }
    }

    // -------------------------------------------------------
    private void ShowMsg(string msg, bool isError)
    {
        string cls = isError ? "msg-err" : "msg-ok";
        LitMsg.Text = string.Format(
            "<div class='{0}'>{1}</div>", cls, msg);
    }
}
